# Numpy(Numerical Python)

In [1]:
import numpy as np

In [7]:
%time array=np.arange(1000000)

CPU times: total: 0 ns
Wall time: 2 ms


In [8]:
print(array)

[     0      1      2 ... 999997 999998 999999]


In [10]:
%time my_list=list(range(100000))

CPU times: total: 0 ns
Wall time: 4 ms


In [11]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [12]:
type(array)

numpy.ndarray

In [13]:
type(my_list)

list

In [17]:
array.dtype

dtype('int32')

In [18]:
%time for _ in range(10):array2=array*2
    

CPU times: total: 46.9 ms
Wall time: 23.9 ms


In [19]:
array2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [20]:
%time for _ in range(10):my_list=[x*2 for x in my_list]

CPU times: total: 109 ms
Wall time: 120 ms


In [21]:

my_list

[0,
 1024,
 2048,
 3072,
 4096,
 5120,
 6144,
 7168,
 8192,
 9216,
 10240,
 11264,
 12288,
 13312,
 14336,
 15360,
 16384,
 17408,
 18432,
 19456,
 20480,
 21504,
 22528,
 23552,
 24576,
 25600,
 26624,
 27648,
 28672,
 29696,
 30720,
 31744,
 32768,
 33792,
 34816,
 35840,
 36864,
 37888,
 38912,
 39936,
 40960,
 41984,
 43008,
 44032,
 45056,
 46080,
 47104,
 48128,
 49152,
 50176,
 51200,
 52224,
 53248,
 54272,
 55296,
 56320,
 57344,
 58368,
 59392,
 60416,
 61440,
 62464,
 63488,
 64512,
 65536,
 66560,
 67584,
 68608,
 69632,
 70656,
 71680,
 72704,
 73728,
 74752,
 75776,
 76800,
 77824,
 78848,
 79872,
 80896,
 81920,
 82944,
 83968,
 84992,
 86016,
 87040,
 88064,
 89088,
 90112,
 91136,
 92160,
 93184,
 94208,
 95232,
 96256,
 97280,
 98304,
 99328,
 100352,
 101376,
 102400,
 103424,
 104448,
 105472,
 106496,
 107520,
 108544,
 109568,
 110592,
 111616,
 112640,
 113664,
 114688,
 115712,
 116736,
 117760,
 118784,
 119808,
 120832,
 121856,
 122880,
 123904,
 124928,
 125

In [22]:
num=np.random.randn(3,3)

In [23]:
num

array([[-0.22597633, -0.08035176, -1.04804769],
       [-0.91392103,  1.47457478,  0.66841238],
       [-1.55773994,  0.54753589, -0.19753172]])

In [24]:
num*3

array([[-0.67792899, -0.24105529, -3.14414306],
       [-2.7417631 ,  4.42372433,  2.00523714],
       [-4.67321981,  1.64260767, -0.59259515]])

In [25]:
arr=np.arange(64).reshape(8,8)

In [26]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [27]:
arr.shape

(8, 8)

In [28]:
arr.ndim

2

In [33]:
arr3d=arr.reshape(4,4,4)

In [34]:
arr3d


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [41]:
arr4d=arr.reshape(16,2,2)

In [42]:
arr4d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43]],

       [[44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51]],

       [[52, 53],
        [54, 55]],

       [[56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63]]])

In [50]:
arr=np.zeros_like(arr3d)

In [51]:
arr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [54]:
arr=np.zeros(3)

In [55]:
arr

array([0., 0., 0.])

In [64]:
data=np.zeros((2,3))

In [65]:
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
data=np.ones((6,5))

In [68]:
data

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
data=np.eye(3,3)

In [72]:
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
data=np.full(2,2)

In [74]:
data

array([2, 2])

In [75]:
data=np.full((4,5),10)

In [76]:
data

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [77]:
my_list=np.array([[2,3,4],[5,6,7],[8,9,0]])

In [78]:
my_list

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [79]:
my_list[1,2]

7

In [80]:
n1=np.arange(36).reshape(6,6)

In [81]:
n2=np.arange(36).reshape(6,6)

In [84]:
%time n1*n2

CPU times: total: 0 ns
Wall time: 0 ns


array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [85]:
%time n1@n2

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 330,  345,  360,  375,  390,  405],
       [ 870,  921,  972, 1023, 1074, 1125],
       [1410, 1497, 1584, 1671, 1758, 1845],
       [1950, 2073, 2196, 2319, 2442, 2565],
       [2490, 2649, 2808, 2967, 3126, 3285],
       [3030, 3225, 3420, 3615, 3810, 4005]])

# Numpy Array Basic Indexing & slicing

In [1]:
import numpy as np

In [2]:
arr2d=np.arange(49).reshape(7,7)

In [3]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [4]:
arr2d[4,5]

33

In [7]:
arr2d[5][6]

41

In [8]:
arr3d=np.arange(120).reshape(3,20,2)

In [9]:
arr3d

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9],
        [ 10,  11],
        [ 12,  13],
        [ 14,  15],
        [ 16,  17],
        [ 18,  19],
        [ 20,  21],
        [ 22,  23],
        [ 24,  25],
        [ 26,  27],
        [ 28,  29],
        [ 30,  31],
        [ 32,  33],
        [ 34,  35],
        [ 36,  37],
        [ 38,  39]],

       [[ 40,  41],
        [ 42,  43],
        [ 44,  45],
        [ 46,  47],
        [ 48,  49],
        [ 50,  51],
        [ 52,  53],
        [ 54,  55],
        [ 56,  57],
        [ 58,  59],
        [ 60,  61],
        [ 62,  63],
        [ 64,  65],
        [ 66,  67],
        [ 68,  69],
        [ 70,  71],
        [ 72,  73],
        [ 74,  75],
        [ 76,  77],
        [ 78,  79]],

       [[ 80,  81],
        [ 82,  83],
        [ 84,  85],
        [ 86,  87],
        [ 88,  89],
        [ 90,  91],
        [ 92,  93],
        [ 94,  95],
        [ 96,  97],
        [ 98,  9

In [14]:
arr1d=np.arange(15)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
sliced=arr1d[4:10:2]
sliced

array([4, 6, 8])

In [23]:
sliced=arr1d[-1:6:2]

In [24]:
sliced

array([], dtype=int32)

In [26]:
# [start_row:end_row   ,   start_col:end_col]   slicing for 2d 

arr2d[3:5,1:3]

array([[22, 23],
       [29, 30]])

In [27]:
arr2d[0:,6:]

array([[ 6],
       [13],
       [20],
       [27],
       [34],
       [41],
       [48]])

# Boolean Indexing

In [2]:
import numpy as np
name=np.array(['ali','aman','ameen','anas','aleem'])
name

array(['ali', 'aman', 'ameen', 'anas', 'aleem'], dtype='<U5')

In [4]:
data=np.random.randn(3,3)
data

array([[-0.07320103, -0.79098809, -1.19161501],
       [ 0.16769534,  0.07682122, -0.63537973],
       [ 0.39347454, -0.03725136,  0.29881231]])

In [5]:
name=='ameen'

array([False, False,  True, False, False])

In [10]:
arr=np.arange(45).reshape(9,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [11]:
arr[[3,7,8]]

array([[15, 16, 17, 18, 19],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [13]:
arr[[True,False,False,True,False,False,True,False,True]]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [14]:
arr<43

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [15]:
arr[arr<43]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42])

In [19]:
data=np.array([2,4,6,8,5,8,4,0,9]).reshape(3,3)
data

array([[2, 4, 6],
       [8, 5, 8],
       [4, 0, 9]])

In [20]:
data%2==0

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [21]:
data[data%2==0]

array([2, 4, 6, 8, 8, 4, 0])

In [23]:
data[[0,1]]

array([[2, 4, 6],
       [8, 5, 8]])